name: Continuous integration
on: [pull_request]

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        drupal_version: ['8.8', '8.9', '9.0']
        module: ['factory_lollipop']
        experimental: [ false ]
        include:
          - drupal_version: '9.1'
            module: 'factory_lollipop'
            experimental: true

    steps:
      - uses: actions/checkout@v1
      - run: docker-compose -f docker-compose.yml pull --include-deps drupal
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml build --pull --build-arg BASE_IMAGE_TAG=${{ matrix.drupal_version }} drupal
      - name: Run tests
        run: docker-compose -f docker-compose.yml run -u www-data drupal phpunit --no-coverage --group=${{ matrix.module }} --configuration=/var/www/html/phpunit.xml
        continue-on-error: ${{ matrix.experimental }}
